# Config File
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'syntax'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/assets/img/common/motherboard.jpg"

exclude:
  - CNAME
  - README.md
