# Config File
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'syntax'

url: http://www.aarondgordon.com

permalink: /:categories/:slug/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
      image: "/assets/img/common/motherboard.jpg"

exclude:
  - CNAME
  - README.md
